export const BACKEND_AUTH_SCHEME = "Bearer"

export const BACKEND_DEFAULT_TIMEOUT_MS = 30_000

export const BACKEND_DEFAULT_ACCESS_TOKEN_COOKIE_NAME = "mr_impot_access_token"
export const BACKEND_DEFAULT_REFRESH_TOKEN_COOKIE_NAME = "mr_impot_refresh_token"

export const BACKEND_DEFAULT_ACCESS_TOKEN_COOKIE_MAX_AGE_SECONDS = 60 * 60
export const BACKEND_DEFAULT_REFRESH_TOKEN_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 30

export const BACKEND_DEFAULT_INTERNAL_API_BASE_PATH = "/api"
